import React from "react";
import { Grid } from "@mui/material";
import DataCard from "@/components/Dashboard/DataCard";

const DataRibbon = ({
  totalFreelancers,
  totalEarnings,
  avgHourlyRate,
  avgSuccessRate,
}) => {
  return (
    <Grid
      container
      spacing={2}
      justifyContent="center"
      alignItems="center"
      style={{
        marginTop: "0.1px",
        overflowX: "auto",
        flexWrap: "nowrap",
        padding: "10px",
      }}
    >
      <Grid item>
        <DataCard
          title="Total Freelancers"
          value={(totalFreelancers ?? 0).toString()}
          description="Total number of freelancers in the dataset"
        />
      </Grid>
      <Grid item>
        <DataCard
          title="Total Earnings (USD)"
          value={`$${(totalEarnings ?? 0).toLocaleString()}`}
          description="Total revenue generated by freelancers"
        />
      </Grid>
      <Grid item>
        <DataCard
          title="Avg. Hourly Rate"
          value={`$${(avgHourlyRate ?? 0).toFixed(2)}/h`}
          description="Average hourly rate of freelancers"
        />
      </Grid>
      <Grid item>
        <DataCard
          title="Avg. Success Rate"
          value={`${(avgSuccessRate ?? 0).toFixed(1)}%`}
          description="Average job success rate of freelancers"
        />
      </Grid>
    </Grid>
  );
};

export default DataRibbon;
