import React from "react";
import { Grid } from "@mui/material";
import DataCard from "@/components/Dashboard/DataCard";

const DataRibbon = ({
  totalFreelancers,
  totalEarnings,
  avgHourlyRate,
  avgSuccessRate,
}) => {
  return (
    <Grid
      container
      spacing={2}
      justifyContent="center"
      alignItems="flex-start"
      style={{
        marginTop: "0.1px",
        display: "flex",
        flexWrap: "wrap",
        overflow: "hidden", // ✅ Empêche tout scroll inutile
        padding: "10px",
        maxWidth: "100%",
        height: "auto", // ✅ S'assure qu'il ne force pas de hauteur
      }}
    >
      <Grid item style={{ maxWidth: "100%", height: "auto" }}>
        <DataCard
          title="Total Freelancers"
          value={(totalFreelancers ?? 0).toString()}
          description="Total number of freelancers in the dataset"
        />
      </Grid>
      <Grid item style={{ maxWidth: "100%", height: "auto" }}>
        <DataCard
          title="Total Earnings (USD)"
          value={`$${(totalEarnings ?? 0).toLocaleString()}`}
          description="Total revenue generated by freelancers"
        />
      </Grid>
      <Grid item style={{ maxWidth: "100%", height: "auto" }}>
        <DataCard
          title="Avg. Hourly Rate"
          value={`$${(avgHourlyRate ?? 0).toFixed(2)}/h`}
          description="Average hourly rate of freelancers"
        />
      </Grid>
      <Grid item style={{ maxWidth: "100%", height: "auto" }}>
        <DataCard
          title="Avg. Success Rate"
          value={`${(avgSuccessRate ?? 0).toFixed(1)}%`}
          description="Average job success rate of freelancers"
        />
      </Grid>
    </Grid>
  );
};

export default DataRibbon;
